# docker-compose up -d
version: '3'

services:

  eureka:
    image: eureka-server:latest
    ports:
      - 9000:9000

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
#    ports:
#      - 3307:3306

  contact-validator:
    image: contact-validator:latest
    ports:
      - 8084:8084
    links:
      - mysql:dbserver
      - eureka:eureka

  contact-service:
    image: contact-service:latest
    ports:
      - 8083:8083
    links:
      - mysql:dbserver
      - eureka:eureka
