spring:
  application:
    name: contact-validator-service

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
#      defaultZone: ${EUREKA_URI:http://eureka:9000/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    org:
#      springframework: debug
      hibernate:
        SQL: debug